title: Data 100
description: Principles and Techniques of Data Science
author: UC Berkeley
baseurl: ~ # the subpath of your site, e.g. /blog
url: 'https://ds100.org' # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
remote_theme: "just-the-docs/just-the-docs@v0.10.1"
plugins:
  - jekyll-remote-theme
color_scheme: light
search_enabled: true
permalink: pretty